import { AdminPathEnums } from "../enums/AdminEnums";
import {
  getRouteAdmin,
  getRouteAdminAboutInstitute,
  getRouteAdminAddAdverts,
  getRouteAdminAddNews,
  getRouteAdminAddUser,
  getRouteAdminAdverts,
  getRouteAdminAdvertsDetails,
  getRouteAdminAdviceInstitute,
  getRouteAdminNewDetails,
  getRouteAdminNews,
  getRouteAdminPhotoGallery,
  getRouteAdminSettings,
  getRouteAdminUserDetails,
  getRouteAdminUsers,
  getRouteAdminDepartmentFaculty,
  getRouteAdminDepartments,
  getRouteAdminDocuments,
  getRouteFaculties,
  getRouteAdminFaculty,
  getRouteAdminScientificFaculty,
  getRouteAdminAboutDepartment,
  getRouteAdminHistoryDepartment,
  getRouteAdminStructureDepartment,
  getRouteAdminSpiritualDepartment,
  getRouteAdminMethodologicalDepartment,
  getRouteAdminResearchDepartment,
  getRouteAdminScientificDepartment,
  getRouteAdminInternationalDepartment,
  getRouteAdminScientific,
  getRouteAdminEditUser,
  getRouteAdminAdvertsEdit,
  getRouteAdminEditNew,
  getRouteAdminEdit,
  getRouteAdminQualificationFaculty,
  getRouteAdminHistoryFaculty,
  getRouteAdminStructureFaculty,
  getRouteAdminCouncilFaculty,
  getRouteAdminMethodologicalFaculty,
  getRouteAdminResearchFaculty,
  getRouteAdminInfoInstitute,
  getRouteAdminRegulationsInstitute,
  getRouteAdminStructureInstitute,
  getRouteAdminStatuteInstitute,
  getRouteAdminCertificateInstitute,
  getRouteAdminEducationalInstitute,
  getRouteAdminLaboratoryInstitute,
  getRouteAdminStudentsInstitute,
} from "../getPaths/AdminGetPaths";

export const AdminPathNames: Record<AdminPathEnums, string> = {
  [AdminPathEnums.ADMIN]: getRouteAdmin(),
  [AdminPathEnums.ADMIN_EDIT]: getRouteAdminEdit(),
  [AdminPathEnums.ADMIN_USERS]: getRouteAdminUsers(),
  [AdminPathEnums.ADMIN_USERS_DETAIL]: getRouteAdminUserDetails(""),
  [AdminPathEnums.ADMIN_USERS_ADD]: getRouteAdminAddUser(),
  [AdminPathEnums.ADMIN_USERS_EDIT]: getRouteAdminEditUser(""),
  [AdminPathEnums.ADMIN_NEWS]: getRouteAdminNews(),
  [AdminPathEnums.ADMIN_NEWS_ADD]: getRouteAdminAddNews(),
  [AdminPathEnums.ADMIN_NEWS_DETAIL]: getRouteAdminNewDetails(""),
  [AdminPathEnums.ADMIN_NEWS_EDIT]: getRouteAdminEditNew(""),
  [AdminPathEnums.ADMIN_ADVERTS]: getRouteAdminAdverts(),
  [AdminPathEnums.ADMIN_ADVERTS_ADD]: getRouteAdminAddAdverts(),
  [AdminPathEnums.ADMIN_ADVERTS_DETAIL]: getRouteAdminAdvertsDetails(""),
  [AdminPathEnums.ADMIN_ADVERTS_EDIT]: getRouteAdminAdvertsEdit(""),
  [AdminPathEnums.ADMIN_PHOTO_GALLERY]: getRouteAdminPhotoGallery(),
  [AdminPathEnums.ADMIN_ABOUT_INSTITUTE]: getRouteAdminAboutInstitute(),
  [AdminPathEnums.ADMIN_INFORMATION_INSTITUTE]: getRouteAdminInfoInstitute(),
  [AdminPathEnums.ADMIN_STRUCTURE_INSTITUTE]: getRouteAdminStructureInstitute(),
  [AdminPathEnums.ADMIN_STATUTE_INSTITUTE]: getRouteAdminStatuteInstitute(),
  [AdminPathEnums.ADMIN_CERTIFICATES_INSTITUTE]:
    getRouteAdminCertificateInstitute(),
  [AdminPathEnums.ADMIN_REGULATIONS_INSTITUTE]:
    getRouteAdminRegulationsInstitute(),
  [AdminPathEnums.ADMIN_EDUCATIONAL_INSTITUTE]:
    getRouteAdminEducationalInstitute(),
  [AdminPathEnums.ADMIN_LABORATORY_INSTITUTE]:
    getRouteAdminLaboratoryInstitute(),
  [AdminPathEnums.ADMIN_STUDENTS_INSTITUTE]: getRouteAdminStudentsInstitute(),
  [AdminPathEnums.ADMIN_ADVICE_INSTITUTE]: getRouteAdminAdviceInstitute(""),
  [AdminPathEnums.ADMIN_DOCUMENTS]: getRouteAdminDocuments(""),
  [AdminPathEnums.ADMIN_SCIENTIFIC]: getRouteAdminScientific(""),
  [AdminPathEnums.ADMIN_FACULTIES]: getRouteFaculties(),
  [AdminPathEnums.ADMIN_FACULTY]: getRouteAdminFaculty(""),
  [AdminPathEnums.ADMIN_SCIENTIFIC_FACULTY]: getRouteAdminScientificFaculty(""),
  [AdminPathEnums.ADMIN_QUALIFICATION_MEDICAL_FACULTY]:
    getRouteAdminQualificationFaculty(""),
  [AdminPathEnums.ADMIN_HISTORY_MEDICAL_FACULTY]:
    getRouteAdminHistoryFaculty(""),
  [AdminPathEnums.ADMIN_STRUCTURE_MEDICAL_FACULTY]:
    getRouteAdminStructureFaculty(""),
  [AdminPathEnums.ADMIN_COUNCIL_MEDICAL_FACULTY]:
    getRouteAdminCouncilFaculty(""),
  [AdminPathEnums.ADMIN_METHODOLOGICAL_MEDICAL_FACULTY]:
    getRouteAdminMethodologicalFaculty(""),
  [AdminPathEnums.ADMIN_RESEARCH_WORK_MEDICAL_FACULTY]:
    getRouteAdminResearchFaculty(""),
  [AdminPathEnums.ADMIN_DEPARTMENTS]: getRouteAdminDepartments(),
  [AdminPathEnums.ADMIN_DEPARTMENT_FACULTY]: getRouteAdminDepartmentFaculty(""),
  [AdminPathEnums.ADMIN_ABOUT_DEPARTMENT]: getRouteAdminAboutDepartment(""),
  [AdminPathEnums.ADMIN_HISTORY_DEPARTMENT]: getRouteAdminHistoryDepartment(""),
  [AdminPathEnums.ADMIN_STRUCTURE_DEPARTMENT]:
    getRouteAdminStructureDepartment(""),
  [AdminPathEnums.ADMIN_SPIRITUAL_DEPARTMENT]:
    getRouteAdminSpiritualDepartment(""),
  [AdminPathEnums.ADMIN_METHODOLOGICAL_DEPARTMENT]:
    getRouteAdminMethodologicalDepartment(""),
  [AdminPathEnums.ADMIN_RESEARCH_DEPARTMENT]:
    getRouteAdminResearchDepartment(""),
  [AdminPathEnums.ADMIN_SCIENTIFIC_DEPARTMENT]:
    getRouteAdminScientificDepartment(""),
  [AdminPathEnums.ADMIN_INTERNATIONAL_DEPARTMENT]:
    getRouteAdminInternationalDepartment(""),
  [AdminPathEnums.ADMIN_SETTINGS]: getRouteAdminSettings(),
};
