import { PathEnums } from "../enums/Enums";
import {
  getRouteAboutDepartmentMedicalFaculty,
  getRouteAboutMedicalFaculty,
  getRouteAcademicCouncilAgenda,
  getRouteAcademicCouncilHandouts,
  getRouteAcademicCouncilMembers,
  getRouteAcademicCouncilResolutions,
  getRouteAcademicCouncilStatue,
  getRouteAdmin,
  getRouteAdminAddAdverts,
  getRouteAdminAddNews,
  getRouteAdminAddUser,
  getRouteAdminAdverts,
  getRouteAdminAdvertsDetails,
  getRouteAdminNewDetails,
  getRouteAdminNews,
  getRouteAdminSettings,
  getRouteAdminUserDetails,
  getRouteAdminUsers,
  getRouteAuth,
  getRouteCouncilMedicalFaculty,
  getRouteDepartmentsMedicalFaculty,
  getRouteEducationalBuildings,
  getRouteGovermentDecisionsPrograms,
  getRouteGovermentPrograms,
  getRouteHistoryDepartmentMedicalFaculty,
  getRouteHistoryMedicalFaculty,
  getRouteInformation,
  getRouteInstituteCertificates,
  getRouteInstituteStatute,
  getRouteInternalRegulations,
  getRouteInternationalPartnershipDepartmentMedicalFaculty,
  getRouteLaboratoryRoom,
  getRouteLaws,
  getRouteLifeStudents,
  getRouteMain,
  getRouteManagement,
  getRouteManagementDetail,
  getRouteMethodologicalDepartmentMedicalFaculty,
  getRouteMethodologicalMedicalFaculty,
  getRouteQualificationMedicalFaculty,
  getRouteResearchWorkDepartmentMedicalFaculty,
  getRouteResearchWorkMedicalFaculty,
  getRouteSitemap,
  getRouteSpiritualDepartment,
  getRouteStructureDepartmentMedicalFaculty,
  getRouteStructureMedicalFaculty,
  getRouteStructureUniversity,
  getRouteStudentScientificSocietyDepartmentMedicalFaculty,
  getRouteStudentScientificSocietyMedicalFaculty,
  getRouteSymbols,
} from "../getPaths/GetPaths";

export const PathNames: Record<PathEnums, string> = {
  [PathEnums.MAIN]: getRouteMain(),
  [PathEnums.AUTH]: getRouteAuth(""),
  [PathEnums.ADMIN]: getRouteAdmin(),
  [PathEnums.ADMIN_USERS]: getRouteAdminUsers(),
  [PathEnums.ADMIN_DETAILS_USER]: getRouteAdminUserDetails(""),
  [PathEnums.ADMIN_ADD_USER]: getRouteAdminAddUser(),
  [PathEnums.ADMIN_NEWS]: getRouteAdminNews(),
  [PathEnums.ADMIN_ADD_NEWS]: getRouteAdminAddNews(),
  [PathEnums.ADMIN_DETAILS_NEWS]: getRouteAdminNewDetails(""),
  [PathEnums.ADMIN_ADVERTS]: getRouteAdminAdverts(),
  [PathEnums.ADMIN_ADD_ADVERTS]: getRouteAdminAddAdverts(),
  [PathEnums.ADMIN_DETAILS_ADVERTS]: getRouteAdminAdvertsDetails("", ""),
  [PathEnums.ADMIN_SETTINGS]: getRouteAdminSettings(),
  [PathEnums.SYMBOLS]: getRouteSymbols("", ""),
  [PathEnums.SITEMAP]: getRouteSitemap(),
  [PathEnums.INFORMATION]: getRouteInformation(),
  [PathEnums.STRUCTURE_UNIVERSITY]: getRouteStructureUniversity(),
  [PathEnums.INSTITUTE_STATUTE]: getRouteInstituteStatute(),
  [PathEnums.INSTITUTE_CERTIFICATES]: getRouteInstituteCertificates(),
  [PathEnums.INTERNAL_REGULATIONS]: getRouteInternalRegulations(),
  [PathEnums.EDUCATIONAL_BUILDINGS]: getRouteEducationalBuildings(),
  [PathEnums.LABORATORY_ROOM]: getRouteLaboratoryRoom(),
  [PathEnums.LIFE_STUDENTS]: getRouteLifeStudents(),
  [PathEnums.ACADEMIC_COUNCIL_STATUE]: getRouteAcademicCouncilStatue(),
  [PathEnums.ACADEMIC_COUNCIL_MEMBERS]: getRouteAcademicCouncilMembers(),
  [PathEnums.ACADEMIC_COUNCIL_AGENDA]: getRouteAcademicCouncilAgenda(),
  [PathEnums.ACADEMIC_COUNCIL_HANDOUTS]: getRouteAcademicCouncilHandouts(),
  [PathEnums.ACADEMIC_COUNCIL_RESOLUTIONS]:
    getRouteAcademicCouncilResolutions(),
  [PathEnums.LAWS]: getRouteLaws(),
  [PathEnums.GOVERMENT_DESCIONS_PROGRAMS]: getRouteGovermentDecisionsPrograms(),
  [PathEnums.GOVERMENT_PROGRAMS]: getRouteGovermentPrograms(),
  [PathEnums.MANAGEMENT]: getRouteManagement(),
  [PathEnums.MANAGEMENT_DETAIL]: getRouteManagementDetail(""),
  [PathEnums.ABOUT_MEDICAL_FACULTY]: getRouteAboutMedicalFaculty(""),
  [PathEnums.QUALIFICATION_MEDICAL_FACULTY]:
    getRouteQualificationMedicalFaculty(""),
  [PathEnums.HISTORY_MEDICAL_FACULTY]: getRouteHistoryMedicalFaculty(""),
  [PathEnums.STRUCTURE_MEDICAL_FACULTY]: getRouteStructureMedicalFaculty(""),
  [PathEnums.COUNCIL_MEDICAL_FACULTY]: getRouteCouncilMedicalFaculty(""),
  [PathEnums.DEPARTMENTS_MEDICAL_FACULTY]:
    getRouteDepartmentsMedicalFaculty(""),
  [PathEnums.METHODOLOGICAL_MEDICAL_FACULTY]:
    getRouteMethodologicalMedicalFaculty(""),
  [PathEnums.STUDENT_SCIENTIFIC_SOCIETY_MEDICAL_FACULTY]:
    getRouteStudentScientificSocietyMedicalFaculty(""),
  [PathEnums.RESEARCH_WORK_MEDICAL_FACULTY]:
    getRouteResearchWorkMedicalFaculty(""),
  [PathEnums.ABOUT_DEPARTMENT_MEDICAL_FACULTY]:
    getRouteAboutDepartmentMedicalFaculty(""),
  [PathEnums.HISTORY_DEPARTMENT_MEDICAL_FACULTY]:
    getRouteHistoryDepartmentMedicalFaculty(""),
  [PathEnums.STRUCTURE_DEPARTMENT_MEDICAL_FACULTY]:
    getRouteStructureDepartmentMedicalFaculty(""),
  [PathEnums.SPIRITUAL_DEPARTMENT_MEDICAL_FACULTY]:
    getRouteSpiritualDepartment(""),
  [PathEnums.METHODOLOGICAL_DEPARTMENT_MEDICAL_FACULTY]:
    getRouteMethodologicalDepartmentMedicalFaculty(""),
  [PathEnums.RESEARCH_WORK_DEPARTMENT_MEDICAL_FACULTY]:
    getRouteResearchWorkDepartmentMedicalFaculty(""),
  [PathEnums.STUDENT_SCIENTIFIC_SOCIETY_DEPARTMENT_MEDICAL_FACULTY]:
    getRouteStudentScientificSocietyDepartmentMedicalFaculty(""),
  [PathEnums.INTERNATIONAL_PARTNERSHIP_DEPARTMENT_MEDICAL_FACULTY]:
    getRouteInternationalPartnershipDepartmentMedicalFaculty(""),
};
